version: '3'

services:
  db:
    container_name: apps-db
    image: mariadb:jammy
    volumes:
      - ./apps_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=my-secret-pw

  phpmyadmin_apps:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
